Update deploy.yml
aaa

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,11 +25,10 @@ jobs:
     - name: Set up SSH
       run: |
         echo "setting up SSH"
-
-        mkdir -p $HOME/.ssh
-        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > $HOME/.ssh/aws_key.pem
-        chmod 600 $HOME/.ssh/aws_key.pem
-        ssh-keyscan ${{ secrets.INSTANCE_IP }} >> $HOME/.ssh/known_hosts
+        mkdir -p $HOME/.ssh || echo ".ssh directory creation failed"
+        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > $HOME/.ssh/aws_key.pem || echo "failed to write SSH private key"
+        chmod 600 $HOME/.ssh/aws_key.pem || echo "failed to set perms on private key"
+        ssh-keyscan ${{ secrets.INSTANCE_IP }} >> $HOME/.ssh/known_hosts || echo "failed to scan SSH key"
         echo "SSH setup complete"
 
     - name: Deploy to EC2 and Restart Bot
