Update deploy.yml
debugging again

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,19 +14,22 @@ jobs:
     - name: Debugging - Check directory and create it
       run: |
         echo "Checking if .ssh directory exists"
-        ls -al /home/runner
-        mkdir -p /home/runner/.ssh || echo "Failed to create /home/runner/.ssh"
+        ls -al $HOME
+        mkdir -p $HOME/.ssh || echo "Failed to create /home/runner/.ssh"
         
     - name: Set up SSH
       run: |
+        echo "setting up SSH"
+        ls -al $HOME/.ssh
+        
         mkdir -p /home/runner/.ssh
-        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > /home/runner/.ssh/aws_key.pem
-        chmod 600 /home/runner/.ssh/aws_key.pem
-        ssh-keyscan ${{ secrets.INSTANCE_IP }} >> /home/runner/.ssh/known_hosts
+        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > $HOME/.ssh/aws_key.pem
+        chmod 600 $HOME/.ssh/aws_key.pem
+        ssh-keyscan ${{ secrets.INSTANCE_IP }} >> $HOME/.ssh/known_hosts
 
     - name: Deploy to EC2 and Restart Bot
       run: |
-        ssh -i /home/runner/.ssh/aws_key.pem ec2-user@${{ secrets.INSTANCE_IP }} << EOF
+        ssh -i $HOME/.ssh/aws_key.pem ec2-user@${{ secrets.INSTANCE_IP }} << EOF
 
           # bot directory
           cd /home/ec2-user/team-3
